/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 6 "init_test.c"
void __globinit_init_test( ) ;
extern void __CrownInit(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCheckSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownEnableSymbolic(int id , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownSetCallerCalleeName(int id , char *fname , char *fname2 )  __attribute__((__crown_skip__)) ;
extern void __CrownHandleReturn(int id , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownReturn(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownCall(int id , unsigned int fid )  __attribute__((__crown_skip__)) ;
extern void __CrownBranch(int id , int bid , unsigned char b , int line , char *fname )  __attribute__((__crown_skip__)) ;
extern void __CrownApply2(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownApply1(int id , int op , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
extern void __CrownClearStack(int id )  __attribute__((__crown_skip__)) ;
extern void __CrownStore(int id , unsigned long addr )  __attribute__((__crown_skip__)) ;
extern void __CrownLoad(int id , unsigned long addr , int type , long long val , double fp_val )  __attribute__((__crown_skip__)) ;
#line 398 "/home/cheong/CROWN/CROWN_tc_generator/bin/../include/crown.h"
extern void __CrownIntInit(int *x , int val , int cnt_sym_var , int ln , char *fname 
                           , ...)  __attribute__((__crown_skip__)) ;
#line 318 "/usr/include/stdio.h"
extern int printf(char    * __restrict  __format  , ...) ;
#line 8 "init_test.c"
int main( ) ;
#line 8 "init_test.c"
static int cnt_symbolic_var  =    1;
#line 6 "init_test.c"
int main( ) 
{ 
  int x ;
  int __retres2 ;

  {
  __globinit_init_test();
  __CrownCheckSymbolic(3, "main");
  __CrownCall(2, 1);
  __CrownClearStack(1);
#line 8
  __CrownIntInit(& x, 7, cnt_symbolic_var, 8, (char *)"init_test.c", "x", 0);
  __CrownLoad(6, (unsigned long )(& cnt_symbolic_var), 5, (long long )cnt_symbolic_var,
              (double )cnt_symbolic_var);
  __CrownLoad(5, (unsigned long )0, 5, (long long )1, (double )1);
  __CrownApply2(4, 0, 5, (long long )(cnt_symbolic_var + 1), (double )(cnt_symbolic_var + 1));
  __CrownStore(7, (unsigned long )(& cnt_symbolic_var));
#line 8
  cnt_symbolic_var ++;
  __CrownLoad(8, (unsigned long )0, 6, (long long )((char    * __restrict  )"x=%d\n"),
              8);
  __CrownLoad(9, (unsigned long )(& x), 5, (long long )x, (double )x);
  __CrownSetCallerCalleeName(10, "main", "printf");
#line 9
  printf((char    * __restrict  )"x=%d\n", x);
  __CrownEnableSymbolic(12, "main");
  __CrownClearStack(11);
  __CrownLoad(15, (unsigned long )(& x), 5, (long long )x, (double )x);
  __CrownLoad(14, (unsigned long )0, 5, (long long )10, (double )10);
  __CrownApply2(13, 16, 5, (long long )(x > 10), (double )(x > 10));
#line 10
  if (x > 10) {
    __CrownBranch(16, 3, 1, __LINE__, __FILE__);
    __CrownLoad(18, (unsigned long )0, 6, (long long )((char    * __restrict  )"x>10\n"),
                8);
    __CrownSetCallerCalleeName(19, "main", "printf");
#line 11
    printf((char    * __restrict  )"x>10\n");
    __CrownEnableSymbolic(21, "main");
    __CrownClearStack(20);
  } 
    #line 10
    else {
    __CrownBranch(17, 4, 0, __LINE__, __FILE__);
    __CrownLoad(22, (unsigned long )0, 6, (long long )((char    * __restrict  )"x<=10\n"),
                8);
    __CrownSetCallerCalleeName(23, "main", "printf");
#line 13
    printf((char    * __restrict  )"x<=10\n");
    __CrownEnableSymbolic(25, "main");
    __CrownClearStack(24);
  }
  __CrownLoad(26, (unsigned long )0, 5, (long long )0, (double )0);
  __CrownStore(27, (unsigned long )(& __retres2));
#line 14
  __retres2 = 0;
  __CrownLoad(28, (unsigned long )(& __retres2), 5, (long long )__retres2, (double )__retres2);
  __CrownReturn(29);
#line 6
  return (__retres2);
}
}
void __globinit_init_test( ) 
{ 


  {
  __CrownInit(30);
}
}
